before_script:


image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  GIT_SUBMODULE_STRATEGY: normal

services:
- docker:dind

stages:
- docs
- test

test_build:
  cache:
        key: "$CI_COMMIT_REF_SLUG"
  stage: test
  tags: 
  - RapidsDL
  script:
  - pwd
  - cd nv-tabular/; docker run --runtime=nvidia --rm -p 48888:8888 -p 48787:8787 -p 48786:8786 -p 43000:3000 --ipc=host --name dev_tip_test -v $(pwd):/rapidsdl/ gitlab-master.nvidia.com:5005/rapidsdl/docker/rapidsdl_nite:latest /bin/bash -c "source activate rapids && cd /rapidsdl/ &&  py.test --cov-config tests/unit/.coveragerc --cov-report term-missing --cov-fail-under 83 --cov=. tests"

pages:
  stage: docs
  tags:
  - RapidsDL
  script:
    - cd nv-tabular/docs/
    - make html
    - cp -r build/html/ public
  artifacts:
    paths:
      - public
